unjs/website

app.vue
components/project-card.vue

The new design looks great!
I only wanted to slightly improve the general readability of the project cards and project details.
- **project-cards:** Increased contrast for star count on project cards
- **project-cards:** Removed unnecessary markup
- Increased line-height across the site

improved readability

---

pages/[name].vue
server/api/repos.ts

Resolve current 500

---

app.vue

I added the main footer to show copyright and some related links.
I hope someone implement better design later (e.g. Twitter and GitHub icons as in Nuxt Official site).
Is there any other link that I should add?
Let me request @manniL's review as suggested by GitHub. 🙌

feat: add footer

---

content/0.index.md
content/1.packages.md
content/_no-articles.md

-
Fix some typos found when navigating the website. Love the design btw!

fix: some typos

---

content/4.packages/cookie-es.md

Fixes typo in github project URL.

fix: link to cookie-es documentation

---

content/4.packages/cookie-es.md

Fix a typo in the description of cookie-es

fix: typo in cookie-es description

---

components/content/home/HomeHero.vue
components/content/home/HomeHeroEyeBrow.vue
content/0.index.md

This PR add a default eye brow is no one is provided.

fix: update home hero eye brow

---

components/puzzle/Puzzle.vue
components/puzzle/PuzzlePart.vue
content/0.index.md

fix https://github.com/unjs/website/issues/37
- Simplified https://github.com/unjs/website/blob/main/components/puzzle/Puzzle.vue, removed magic numbers.
- Use `pointer-events-none` on child div to remove "doom flickers" (https://www.joshwcomeau.com/animation/css-transitions/#doom-flicker-13)
- Use transforms for better performance.

fix: puzzle transition

---

components/content/AnotherArticle.vue
components/content/ProseTable.vue
components/content/ProseTbody.vue
components/content/ProseThead.vue
layouts/blog.vue
uno.config.ts

fix: optimize blog styles

---

content/5.blog/2023-08-25-nitro-2.6.md
content/5.blog/2023-08-25-nitro.md

https://unjs.pages.dev/blog/2023-08-25-nitro?preview=25426666ba8e287ec38e10d619e3e01e0d4b8f45a75f943cbfb0d09491614471

feat: add blog for nitro 2.6 announcement

---

components/app/AppHeader.vue

fix #75
I update the header design to prepare for the upcoming new pages.

fix: clean header and update social icons size

---

components/content/home/HomeHeroEyeBrow.vue

fix: home eyebrow

---

components/content/AnotherArticle.vue
content/5.blog/2023-08-25-nitro-2.6.md

fix #91
This PR a better block to make links between articles (better than juste a simple link to the article).

feat: add another-article component in nitro blog post

---

.github/workflows/ci.yml

ci: use node 20.5

---

.github/workflows/autofix.yml

ci: add autofix

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/content-report.yml
.github/ISSUE_TEMPLATE/feature-report.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/semantic-pull-request.yml

fix #109
fix #112
This PR add the `content` type to PR validation and to the PR template.

chore: update pull request template

---

assets/app.css
layouts/blog-post.vue
nuxt.config.ts

fix #68
Add "on this page" for the mobile version of the blog.

feat: add on this page on mobile

---

components/app/AppButton.vue
components/package/PackageExternalLink.vue
components/package/PackageHeader.vue
components/package/PackageMetadata.vue
components/packages/PackagesExternalLink.vue
layouts/package.vue

fix #102
This PR update some design issues.

fix: update package page

---

.github/workflows/ci.yml

Add build in CI since the deploy command is nuxt build. This could help us to debug the build process.

ci: add build in ci

---

nuxt.config.ts
server/api/search.txt.ts
server/routes/blog/rss.xml.ts
server/routes/build/rss.xml.ts
server/routes/explore/rss.xml.ts
server/routes/learn/rss.xml.ts
server/routes/rss.xml.ts

fix #164
Update routeRules to clean the Nuxt Config and to better use features of Nuxt

refactor: remove route-rules in favor of routes

---

components/content/home/HomeHero.vue

fix: home hero puzzle

---

content/_footer-license.md

the link to licence was broken.

fix: update licence link

---

nuxt.config.ts

fix: enable inlining css

---

components/content/DocumentDrivenNotFound.vue

fix #44
This add a custom not found page for the website.

feat: add custom document driven not found

---

content/5.blog/2023-08-15-h3-towards-the-edge-of-the-web.md

chore: add missing `async` keyword in H3 blog post

---

.github/workflows/generate-monthly-updates.yml
scripts/releases-article.ts
scripts/repos-packages.ts
scripts/types.ts
scripts/update-packages.ts
scripts/utils/github.ts

ci: automate monthly updates

---

components/content/design-kit/DesignKitTypography.vue
content/design-kit.md

fix: typo in design-kit

---

content/design-kit.md

Add white logo in order to tell to people that the same logo can be used on both white and black backgrounds.

content: add white logo to design kit

---

components/content/design-kit/DesignKitPackageLogos.vue
content/design-kit.md

Add package logos to design kit in order to allow people to reuse them for marketing purposes.

feat: add package logos to design kit

---

nuxt.config.ts
server/api/content/packages.json.ts

Exposing packages content can help to build external service in sync with unjs.io

feat: expose packages through api

---

components/app/AppSearchDialog.vue
pages/blog/index.vue
pages/packages/index.vue

fix #166
This PR update the way event are sent to plausible.

fix: better plausible

---

pages/packages/[...slug].vue

#240 
Fix issue with package pages. 
Today I studied the description of the packages and caught 404. After a little research, I noticed that a small mistake was made in pr #238 . I will be very happy to fix it. If there are suggestions to improve my PR, I am ready to make them promptly in order to fix the problem in the best way.

fix: examples link

---

bin/commands/generate.ts
bin/commands/generate/content.ts
bin/utils/content.ts
bin/utils/slugify.ts
content/5.blog/.template.md
content/5.blog/2023-08-15-h3-towards-the-edge-of-the-web.md
content/5.blog/2023-08-25-nitro-2-6.md
package.json
pnpm-lock.yaml

In order to help us to create articles for the blog, I've added a new command to the CLI that will create a new blog post with the correct template and filename.

ci: add a command to generate file from template

---

components/OgImage/OgImagePackage.vue
pages/packages/[...slug].vue

fix #80
close #81
Add a custom Og Image for every packages.

feat: add package og image

---

pages/blog/[...slug].vue
pages/blog/index.vue
pages/categories/[category].vue
pages/categories/index.vue
pages/design-kit.vue
pages/index.vue
pages/packages/[...slug].vue
pages/packages/index.vue
pages/rss.vue
pages/search.vue

feat: update schema org

---

content/5.blog/2023-08-15-h3-towards-the-edge-of-the-web.md

none
when using the provided code snippet, I get
- TS compiler error : `Property 'data' does not exist on type 'SafeParseReturnType<...`
- and error : `Cannot read properties of undefined (reading 'issues')` (when calling `result.error.issues`)

fix: typo in "Runtime + Type-Safe Request Utils" example

---

components/app/AppAlert.vue
components/content/Caution.vue
components/content/Important.vue
components/content/Note.vue
components/content/Tip.vue
components/content/Warning.vue
nuxt.config.ts
package.json
pnpm-lock.yaml
server/api/github/[owner]/[repo]/readme.ts
server/plugins/contents.ts

feat: add support for markdown blockquotes

---

nuxt.config.ts

fix: remove cache content

---

nuxt.config.ts

refactor: schema org identity

---

components/app/AppAlert.vue
components/content/AnotherArticle.vue
components/content/ReadMore.vue
package.json
pnpm-lock.yaml

feat: add read-more component

---

composables/useBlog.ts
composables/usePackages.ts

Use `useAsyncData` to put some data in payload (to avoid a refetch).

fix: use filters

---

components/content/ProseA.vue

fix #265 
This PR remove the `rel="nofollow"` and replace it with a `noopener` if unjs.io domain and `noopener noreferrer` if not.

fix: prose a

---

nuxt.config.ts

fix #279
this make the build time stricter.

ci: fail nitro on error

---

nuxt.config.ts
package.json
pnpm-lock.yaml

fix #278 
main (https://github.com/unjs/website/actions/runs/7729936180/job/21074219751)
- time to generate: 1.42
this pr:
- time to generate: 1.24

chore: remove studio

---

bin/types.ts
composables/useBlog.ts
composables/useLearnArticles.ts
package.json
pnpm-lock.yaml

chore: update nuxt to 3.10

---

tailwind.config.ts

Fix a firefox issue where the default font is a serif one.

chore: update tailwind fallback fonts

---

package.json
pnpm-lock.yaml

chore: update nuxt fonts
